const fs=require('fs'),path=require('path');const {ROOT,route,routes}=require('./foundation.cjs'),{launch}=require('./browser.cjs'),{collect}=require('./translation-units.cjs');
const source=require('./translation-source.json'),entries=[...require('./translations-a.cjs'),...require('./translations-b.cjs'),...require('./translations-c.cjs')];
const preserved=[1,2,4,7,8,9,10,13,17,30,33,43,55,58,64,65,71,75,77,79,81,93,94,102,149,158,168,173,191,201,206,243,265,279,282,285,302,361,370,377,379];
const passageTranslations={341:['Permission to inhabit your body','Permiso para habitar el cuerpo'],342:['Body as temple, pleasure without guilt','Cuerpo templo, placer sin culpa'],343:['Permission to feel your inner waters','Permiso para sentir las aguas internas'],344:['The dance of Shiva-Shakti','La danza de Shiva-Shakti'],345:['The voice of pleasure','La voz del placer'],346:['Mirrors of love','Espejos del amor'],347:['Consecration of the rose','Consagración de la rosa']};
const byId=Object.fromEntries(entries.map(([id,en,es])=>[id,[en,es]]));for(const s of source)if(!byId[s.id]&&!preserved.includes(s.id)&&!passageTranslations[s.id])throw Error('Missing unit '+s.id);
const titles={templo:['The Temple','El Templo'],caminhos:['Paths','Caminos'],arte:['Art','Arte']};
(async()=>{const b=await launch(),report=[];try{const p=await b.newPage();await p.route('**/*',r=>r.abort());for(const key of Object.keys(routes))for(const lang of [1,2]){
 const html=fs.readFileSync(path.join(ROOT,route(key),'index.html'),'utf8'),locale=lang===1?'en':'es';
 const result=await p.evaluate(({html,key,lang,locale,source,byId,preserved,passageTranslations,paths,code,title})=>{
 const d=new DOMParser().parseFromString(html,'text/html'),get=eval('('+code+')'),lookup=new Map(source.map(s=>[s.text,s]));const units=get(d);let translated=0,quotes=0,names=0;
 for(const u of units){const s=lookup.get(u.text);if(!s)throw Error('Unknown PT unit '+u.text);if(preserved.includes(s.id)){names++;continue}const named=passageTranslations[s.id];if(named){const owner=u.el.nodeType===3?u.el.parentElement:u.el;owner.lang='pt-BR';const gloss=d.createElement('span');gloss.className='named-translation';gloss.lang=locale;gloss.textContent='['+named[lang-1]+']';owner.append(gloss);names++;continue}const value=byId[s.id][lang-1];if(u.proof){u.el.lang='pt-BR';const gloss=d.createElement('p');gloss.className='translation';gloss.lang=locale;gloss.textContent='['+value+']';u.el.after(gloss);quotes++;}else if(u.type==='attribute')u.el.setAttribute(u.attr,value.replace(/<[^>]*>/g,' '));else if(u.type==='text')u.el.textContent=value.replace(/<[^>]*>/g,' ');else u.el.innerHTML=value;translated++;}
 d.documentElement.lang=locale;d.body.dataset.language=locale;d.body.dataset.stage='L6';d.querySelector('meta[property="og:locale"]').content=locale==='en'?'en_US':'es_ES';d.querySelector('link[rel="canonical"]').href='https://thegoldentemple.io'+paths[key][lang];if(title)d.title=title+' | Prana Ka';
 const routeMap=Object.fromEntries(Object.values(paths).map(a=>[a[0],a[lang]]));for(const a of d.querySelectorAll('a[href^="/"]:not(.language-nav a)')){const [base,hash]=a.getAttribute('href').split('#');if(routeMap[base])a.setAttribute('href',routeMap[base]+(hash?'#'+hash:''));}
 for(const a of d.querySelectorAll('.language-nav a')){a.removeAttribute('aria-current');if(a.lang===locale)a.setAttribute('aria-current','page');}
 // Every conversion unit is individually marked; original customer quotations are not transcreated.
 const marked=[];for(const el of d.querySelectorAll('main h1,main h2,main h3,main a,main .hero-statement,main .hero-description,main .hero__lead,main .hero__subhead,main .home-statement,main .home-subhead,main .institution-statement,main .offer,main .price,main .home-closing,main .institution-closing')){el.before(d.createComment(' REVISAR: transcriação '));marked.push({tag:el.tagName,id:el.id||'',section:el.closest('section')?.id||'',text:el.textContent.replace(/\s+/g,' ').trim().slice(0,160)});}
 const depth=d.querySelector('.depth-button');if(depth){depth.dataset.labelOn=locale==='en'?'Disable depth':'Desactivar profundidad';depth.dataset.labelOff=locale==='en'?'Enable depth':'Activar profundidad';depth.dataset.labelError=locale==='en'?'Depth unavailable':'Profundidad no disponible';}
 const sound=d.querySelector('[data-sound]');if(sound){sound.dataset.labelOn=locale==='en'?'Sound on':'Sonido encendido';sound.dataset.labelOff=locale==='en'?'Sound off':'Sonido apagado';sound.dataset.labelError=locale==='en'?'Try listening again':'Volver a intentar';}
 for(const a of d.querySelectorAll('a[href="#descobrir"]'))a.setAttribute('aria-label',locale==='en'?'Explore this page':'Explorar esta página');
 return {html:'<!doctype html>\n'+d.documentElement.outerHTML+'\n',translated,quotes,names,marked};
 },{html,key,lang,locale,source,byId,preserved,passageTranslations,paths:Object.fromEntries(Object.keys(routes).map(k=>[k,[route(k,0),route(k,1),route(k,2)]])),code:collect.toString(),title:titles[key]?.[lang-1]});
 fs.writeFileSync(path.join(ROOT,route(key,lang),'index.html'),result.html);report.push({key,locale,route:route(key,lang),translated:result.translated,originalQuotes:result.quotes,preservedNames:result.names,review:result.marked});console.log(locale,key,result.translated,'units;',result.quotes,'original quotes');
 }
 fs.writeFileSync(path.join(ROOT,'_qa','L6-translations.json'),JSON.stringify({uniqueSourceUnits:source.length,directOrTranscreated:entries.length,preserved,passageTranslations,files:report},null,2));
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
