const fs=require('fs'),path=require('path');const {ROOT,page,write,geometry}=require('./foundation.cjs');const {launch}=require('./browser.cjs');
const sourceRoot=path.resolve(ROOT,'..','..');const copy=fs.readFileSync(path.join(sourceRoot,'COPY-GOLDEN-TEMPLE-V3.md'),'utf8');
function section(n){const start=copy.indexOf('## D'+n+' ·');const end=copy.indexOf('\n## D',start+5);return copy.slice(start,end===-1?undefined:end)}
function blocks(n){return [...section(n).matchAll(/```\r?\n([\s\S]*?)\r?\n```/g)].map(m=>m[1])}
const d1=blocks(1),d7=blocks(7),d8=blocks(8),d11=blocks(11);const img=(file,cls='',eager=false)=>`<img class="${cls}" src="/assets/biblioteca/${file}.webp" width="900" height="900" alt="" ${eager?'fetchpriority="high"':'loading="lazy"'}>`;
(async()=>{const browser=await launch();try{const p=await browser.newPage();await p.route('**/*',r=>r.abort());const data=await p.evaluate(({vu,mentoria,curso})=>{const parse=s=>new DOMParser().parseFromString(s,'text/html');const v=parse(vu),m=parse(mentoria),c=parse(curso);return {proof:v.querySelector('.proof-grid').outerHTML,proofHeading:v.querySelector('.proof-heading h2').innerHTML,proofNote:v.querySelector('.proof-note').textContent,method:m.querySelector('.ser-path').outerHTML,bio:m.querySelector('.guide__statement').nextElementSibling.innerHTML,offers:[{title:'O Templo Dourado',body:m.querySelector('.hero__lead').textContent,cta:'Quero selar minha entrada',route:'/mentoria/'},{title:'Visão Uterina',body:v.querySelector('.hero-description').textContent,cta:'Quero minha Visão Uterina',route:'/visao-uterina/'},{title:'Despertar do Prazer Sagrado',body:c.querySelector('.hero__subhead').textContent,cta:'Quero reabrir a fonte',route:'/curso/'}]};},{vu:fs.readFileSync(path.join(ROOT,'visao-uterina/index.html'),'utf8'),mentoria:fs.readFileSync(path.join(ROOT,'mentoria/index.html'),'utf8'),curso:fs.readFileSync(path.join(ROOT,'curso/index.html'),'utf8')});
const credo=['Aqui o corpo é templo.','O ventre é altar.','A voz é portal.','A arte é oração.','O prazer é meditação.','A sombra é mestra.','O amor é lei.'];
const cards=data.offers.map(o=>`<article class="path-card reveal"><div class="path-card-visual">${img('rosa-dourada')}</div><h3>${o.title}</h3><p>${o.body}</p><a class="text-link" href="${o.route}">${o.cta}<span aria-hidden="true">↗</span></a></article>`).join('');
const main=`<main id="conteudo">
<section class="home-hero" id="inicio" aria-labelledby="home-title" data-composition="1"><div class="home-hero-copy"><p class="eyebrow">${d1[0]}</p><h1 id="home-title">The Golden<br>Temple</h1><p class="home-tagline">${d1[2]}</p><p class="home-statement">${d1[3]}</p><p class="home-subhead">${d1[4]}</p><a class="button" href="#caminhos">${d1[5]} <span aria-hidden="true">↘</span></a></div><div class="hero-art"><div class="depth-stage" data-state="static">${img('selo-templo','',true)}</div><p class="hero-art-caption">The Golden Temple · Prana Ka</p><button class="depth-button" type="button" aria-pressed="false" hidden>Ativar profundidade</button></div><a class="home-scroll" href="#credo">${d1[7]} ↓</a></section>
<section class="credo fold" id="credo" aria-label="O credo" data-composition="2">${img('ornamento-divisor','ornament')}${credo.map(t=>`<p class="credo-line">${t}</p>`).join('')}<p class="credo-close reveal">Cada mulher caminha no seu ritmo, mas nenhuma caminha sozinha.</p>${geometry()}</section>
<section class="home-portals fold" id="portais" aria-labelledby="portals-title" data-composition="3"><p class="eyebrow">Os dois portais</p><h2 id="portals-title">Por onde o teu corpo pede para começar?</h2><div class="portal-pair"><article class="portal reveal"><div class="portal-visual">${img('portal-arco-rosa')}</div><div><h3>Despertar do Prazer Sagrado</h3><p>A primeira travessia. Sete meditações que reconduzem você ao prazer como presença, e não como performance.</p><a class="text-link" href="/curso/">Começar pelo corpo ↗</a></div></article><article class="portal reveal"><div class="portal-visual">${img('portal-arco-rosa')}</div><div><h3>Mentoria O Templo Dourado</h3><p>A Iniciação Dourada vivida em grupo, com a Prana conduzindo, do primeiro portal à coroação.</p><a class="text-link" href="/mentoria/">Atravessar a jornada inteira ↗</a></div></article></div></section>
<section class="home-school fold" id="escola" aria-labelledby="school-title" data-composition="4"><div class="home-school-art reveal">${img('geometria-flor-da-vida')}</div><div class="home-school-copy reveal"><p class="eyebrow">${d7[1]}</p><h2 id="school-title">${d7[2]}</h2><p>Essa é a missão, e ela explica o resto.</p><p>${d7[3].replace('Essa é a missão, e ela explica o resto. ','')}</p><p>${d7[4]}</p><a class="text-link" href="/o-templo/">O Templo ↗ <span class="route-pending">[EM BREVE]</span></a></div></section>
<section class="home-method fold" id="metodo" aria-labelledby="method-title" data-composition="5"><div class="home-method-heading reveal"><p class="eyebrow">Método S.E.R.</p><h2 id="method-title">A verdade não se pensa. Corporifica-se.</h2>${img('sri-yantra-cobre','method-art')}<a class="text-link" href="/metodo/">Método S.E.R. ↗ <span class="route-pending">[EM BREVE]</span></a></div><div>${data.method}</div>${geometry()}</section>
<section class="home-paths fold" id="caminhos" aria-labelledby="paths-title" data-composition="6"><p class="eyebrow">Os caminhos</p><h2 id="paths-title">Por onde o teu corpo pede para começar?</h2><div class="path-grid">${cards}</div>${geometry()}</section>
<section class="home-art fold" id="arte" aria-labelledby="art-title" data-composition="7"><div class="art-visual reveal">${img('disco-solar')}</div><div class="reveal"><p class="eyebrow">Prana Ka</p><h2 id="art-title">A arte.</h2><div class="music-links"><a data-external="spotify" href="https://open.spotify.com/intl-pt/artist/2VoeKjLxkb4cLrCbHTbojD" target="_blank" rel="noopener noreferrer">Spotify <span aria-hidden="true">↗</span></a><a data-external="youtube" href="https://www.youtube.com/@iampranaka" target="_blank" rel="noopener noreferrer">YouTube <span aria-hidden="true">↗</span></a></div><a class="text-link" href="/arte/">Arte ↗ <span class="route-pending">[EM BREVE]</span></a></div></section>
<section class="home-guide fold" id="prana" aria-labelledby="prana-title" data-composition="8"><div class="home-guide-portrait reveal">${img('prana-golden-temple')}</div><div class="home-guide-copy reveal"><p class="eyebrow">Quem conduz</p><h2 id="prana-title">Prana Ka</h2><blockquote>“Eu guio não porque sei tudo, mas porque vivo tudo.”</blockquote><p>${data.bio}</p><p>${d8[6]}</p><a class="text-link" href="/prana/">Prana Ka ↗ <span class="route-pending">[EM BREVE]</span></a></div></section>
<section class="home-proof fold" id="mulheres" aria-labelledby="proof-title" data-composition="9">${img('rosa-vermelha-orvalho','proof-rose')}<div class="home-proof-heading reveal"><h2 id="proof-title">${data.proofHeading}</h2><p class="proof-note">${data.proofNote}</p></div>${data.proof}<p class="video-pending">[COPY PENDENTE]</p><!-- A inclusão do vídeo da Carol é citada em §8, mas §12 restringe a prova às quatro autoras. Aguardar revisão do contrato. -->${geometry()}</section>
<section class="home-closing fold" id="chamado" aria-labelledby="closing-title" data-composition="10">${img('templo-flutuante-rosas','closing-art')}${img('selo-templo','brand-seal')}<p class="eyebrow">${d11[0]}</p><h2 id="closing-title">${d11[1]}</h2><p>${d11[2]}</p><a class="button" href="#caminhos">${d11[3]} <span aria-hidden="true">↗</span></a><small>${d11[4]}</small></section>
</main><button class="audio-switch" data-sound type="button" aria-expanded="false" aria-controls="sound-panel" hidden>Som desligado ♫</button><aside class="sound-panel" id="sound-panel" hidden aria-label="Ouvir Prana Ka"><p>Ouvir Prana Ka</p><a data-external="spotify" href="https://open.spotify.com/intl-pt/artist/2VoeKjLxkb4cLrCbHTbojD" target="_blank" rel="noopener noreferrer">Abrir Spotify ↗</a><a data-external="youtube" href="https://www.youtube.com/@iampranaka" target="_blank" rel="noopener noreferrer">Abrir YouTube ↗</a><button type="button">Fechar</button></aside>`;
write('/',page('home',main,{css:['pages/oferta','pages/home'],scripts:['hero-25d'],description:d1[4],draft:false}));fs.writeFileSync(path.join(ROOT,'_qa','home-source-map.json'),JSON.stringify({hero:'COPY-GOLDEN-TEMPLE-V3.md D1',credo:'BRIEFING §8.1',portals:'COPY-GOLDEN-TEMPLE-V3.md D10',school:'COPY-GOLDEN-TEMPLE-V3.md D7',method:'mentoria .ser-path',offers:'hero paragraphs from three approved offers',guide:['mentoria d6','COPY-GOLDEN-TEMPLE-V3.md D8'],proof:'visao-uterina .proof-grid',closing:'COPY-GOLDEN-TEMPLE-V3.md D11',pending:['video: §8 versus §12','audio: no direct media asset provided']},null,2));console.log('Home: dez dobras, copy de fontes existentes, 1 pendência sinalizada.');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
