const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..');
const routes={home:['','', ''],templo:['o-templo','the-temple','el-templo'],metodo:['metodo','method','metodo'],caminhos:['caminhos','paths','caminos'],mentoria:['mentoria','mentorship','mentoria'],visao:['visao-uterina','uterine-vision','vision-uterina'],curso:['curso','course','curso'],arte:['arte','art','arte'],prana:['prana','prana','prana']};
const languages=['pt-BR','en','es'];
const names={home:'The Golden Temple',templo:'O Templo',metodo:'Método S.E.R.',caminhos:'Caminhos',mentoria:'O Templo Dourado',visao:'Visão Uterina',curso:'Despertar do Prazer Sagrado',arte:'Arte',prana:'Prana Ka'};
const origin='https://thegoldentemple.io';
const route=(key,lang=0)=>'/'+(lang?languages[lang]+'/':'')+(routes[key][lang]?routes[key][lang]+'/':'');
const mark='<svg viewBox="0 0 40 56" aria-hidden="true"><ellipse cx="20" cy="14" rx="9" ry="12" fill="none" stroke="currentColor" stroke-width="2"/><path d="M20 26v27M5 34h30M2 29l8 5M38 29l-8 5" fill="none" stroke="currentColor" stroke-width="2"/></svg>';
function geometry(){return '<svg class="geometry motion-geometry" viewBox="0 0 240 240" aria-hidden="true"><circle cx="120" cy="120" r="100"/><circle cx="120" cy="120" r="62"/><circle cx="89" cy="120" r="62"/><circle cx="151" cy="120" r="62"/><path d="M120 20 207 170H33Z M120 220 33 70h174Z"/></svg>'}
function header(key,lang){const nav=['templo','metodo','caminhos','arte','prana'].map(k=>`<a href="${route(k,lang)}"${k===key?' aria-current="page"':''}>${names[k]}</a>`).join('');return `<a class="skip-link" href="#conteudo">${['Pular para o conteúdo','Skip to content','Saltar al contenido'][lang]}</a><header class="site-header"><a class="wordmark" href="${route('home',lang)}" aria-label="The Golden Temple — início">${mark}<span class="wordmark-type">The Golden Temple<small>The Art of Living Devotion</small></span></a><nav class="desktop-nav" aria-label="Principal">${nav}</nav><nav class="language-nav" aria-label="Idioma">${languages.map((l,i)=>`<a href="${route(key,i)}" lang="${l}" hreflang="${l}"${i===lang?' aria-current="page"':''}>${['PT','EN','ES'][i]}</a>`).join('')}</nav><details class="mobile-menu"><summary>Menu</summary><nav aria-label="Menu">${nav}</nav></details></header>`}
function footer(lang){return `<footer class="site-footer"><div class="footer-top"><img class="footer-seal" src="/assets/biblioteca/selo-templo.webp" width="900" height="900" alt="" loading="lazy"><p class="footer-brand">The Golden Temple<small>The Art of Living Devotion · Prana Ka</small></p><nav class="footer-links" aria-label="Ofertas"><a href="${route('mentoria',lang)}">O Templo Dourado</a><a href="${route('visao',lang)}">Visão Uterina</a><a href="${route('curso',lang)}">Despertar do Prazer Sagrado</a></nav></div><div class="footer-bottom"><span>Prana Ka · The Golden Temple</span><a href="#conteudo">${['Voltar ao início ↑','Back to top ↑','Volver al inicio ↑'][lang]}</a></div></footer>`}
function page(key,main,{lang=0,css=[],scripts=[],description='',draft=true}={}){return `<!doctype html>\n<html lang="${languages[lang]}">\n<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#481625"><meta name="robots" content="noindex,nofollow"><meta name="description" content="${description.replaceAll('"','&quot;')}"><meta property="og:locale" content="${['pt_BR','en_US','es_ES'][lang]}"><title>${names[key]} | Prana Ka</title><link rel="canonical" href="${origin+route(key,lang)}">${languages.map((l,i)=>`<link rel="alternate" hreflang="${l}" href="${origin+route(key,i)}">`).join('')}<link rel="alternate" hreflang="x-default" href="${origin+route(key)}"><link rel="icon" href="/assets/logos/favicon.svg" type="image/svg+xml"><link rel="preload" as="font" type="font/woff2" href="/assets/fonts/fraunces-latin.woff2" crossorigin><link rel="preload" as="font" type="font/woff2" href="/assets/fonts/manrope-latin.woff2" crossorigin>${['tokens','base','components','motion',...css].map(s=>`<link rel="stylesheet" href="/css/${s}.css">`).join('')}<script src="/js/config.js" defer></script>${['i18n-switch','nav','scroll','reveal','main',...scripts].map(s=>`<script src="/js/${s}.js" defer></script>`).join('')}</head>\n<body class="page-${key}" data-language="${languages[lang]}" data-stage="${draft?'foundation':'L1-L4'}">${header(key,lang)}${main}${footer(lang)}</body></html>\n`}
function write(routePath,html){const filename=path.join(ROOT,routePath,'index.html');fs.mkdirSync(path.dirname(filename),{recursive:true});fs.writeFileSync(filename,html)}
if(require.main===module){for(const key of Object.keys(routes))for(let lang=0;lang<3;lang++){const file=path.join(ROOT,route(key,lang),'index.html');if(fs.existsSync(file))continue;write(route(key,lang),page(key,`<main id="conteudo" class="pending-page"><img class="brand-seal" src="/assets/biblioteca/selo-templo.webp" width="900" height="900" alt=""><p class="eyebrow">The Golden Temple</p><h1>${names[key]}</h1><p>[EM BREVE]</p></main>`,{lang}));}console.log('27 rotas de fundação criadas.');}
module.exports={ROOT,route,routes,page,write,geometry};
