const fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const puppeteer=require('C:/Users/zioni/AppData/Local/npm-cache/_npx/0f94ee7615faf582/node_modules/puppeteer-core');
const root=path.resolve(__dirname,'..','quiz'), pkg=path.resolve(__dirname,'..'), ref=path.join(pkg,'referencia'), out=path.join(pkg,'evidencia','gate');
const refs={list4:5,binary:3,list3:11,grid:2,I1:9,I2:9,I3:9,I4:9,I5:9,result:32};
const types={'html':'text/html; charset=utf-8','js':'text/javascript; charset=utf-8','css':'text/css; charset=utf-8','woff2':'font/woff2','webp':'image/webp'};
const server=http.createServer((req,res)=>{let pathname=new URL(req.url,'http://localhost').pathname;let rel=decodeURIComponent(pathname.replace(/^\/quiz\/?/,''));if(!rel)rel='index.html';let file=path.resolve(root,rel);if(!file.startsWith(root)){res.writeHead(403).end();return}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end(String(err));return}let ext=path.extname(file).slice(1);res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':'no-store'});res.end(data)})});
const wait=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{fs.mkdirSync(path.join(out,'390'),{recursive:true});fs.mkdirSync(path.join(out,'1440'),{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;const browser=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--no-first-run','--no-default-browser-check']});let report={viewports:[],errors:[],external:[],payload:null};
for(const vp of [{width:390,height:844,mobile:true},{width:1440,height:1000,mobile:false}]){const page=await browser.newPage();await page.setViewport({width:vp.width,height:vp.height,isMobile:vp.mobile,hasTouch:vp.mobile});page.on('pageerror',e=>report.errors.push(String(e)));page.on('request',r=>{if(!r.url().startsWith(`http://127.0.0.1:${port}/`)&& !r.url().startsWith('data:'))report.external.push(r.url())});page.on('console',async msg=>{if(msg.text().startsWith('quiz_payload ')){try{const args=msg.args();report.payload=args.length>1?await args[1].jsonValue():null}catch{}}});await page.goto(`http://127.0.0.1:${port}/quiz/index.html`,{waitUntil:'networkidle0'});await page.evaluate(()=>document.fonts.ready);
const snap=async(key)=>{const local=await page.screenshot({type:'png'});const refPath=path.join(ref,String(vp.width),`tela-${String(refs[key]).padStart(2,'0')}.png`);const refData=fs.readFileSync(refPath).toString('base64'), localData=local.toString('base64');const pair=await browser.newPage();await pair.setViewport({width:vp.width*2,height:vp.height+34});await pair.setContent(`<style>*{box-sizing:border-box}body{margin:0;font:14px Arial}.row{display:grid;grid-template-columns:1fr 1fr}.label{height:34px;text-align:center;background:#222;color:#fff;padding:8px}.row img{width:${vp.width}px;height:${vp.height}px;object-fit:contain;display:block}</style><div class="row"><div><div class="label">REFERÊNCIA · TELA ${refs[key]}</div><img src="data:image/png;base64,${refData}"></div><div><div class="label">QUIZ V6 · ${key}</div><img src="data:image/png;base64,${localData}"></div></div>`);await pair.screenshot({path:path.join(out,String(vp.width),`${key}.png`)});await pair.close()};
const click=async sel=>{try{await page.waitForSelector(sel,{visible:true,timeout:5000});await page.click(sel);await wait(120)}catch(e){throw new Error('Falha ao clicar '+sel+' no viewport '+vp.width+': '+(await page.evaluate(()=>document.body.innerText)).slice(0,300)+'; '+e.message)}};
await click('[data-gender]');let ys=[];for(let i=0;i<4;i++){ys.push(await page.$eval('.question-title',e=>Math.round(e.getBoundingClientRect().top)));await click('[data-choice]')};await snap('I1');await click('[data-next]');
await snap('list4');for(let q=0;q<10;q++){if(q===1)await snap('binary');if(q===3)await snap('list3');if(q===7)await snap('grid');if(q===3)await click('[data-score="1.5"]');else await click('[data-score]')}await snap('I2');await click('[data-next]');
for(let q=10;q<15;q++)await click('[data-score]');await snap('I3');await click('[data-next]');for(let q=15;q<20;q++)await click('[data-score]');await snap('I4');await click('[data-next]');for(let q=20;q<25;q++)await click('[data-score]');await snap('I5');await click('[data-next]');await click('[data-desire]');await page.waitForFunction(()=>document.querySelector('.result-banner'),{timeout:5000});await snap('result');const result=await page.evaluate(()=>({body:document.body.innerText,rows:[...document.querySelectorAll('.metric-row')].map(e=>({text:e.innerText,rect:(()=>{let r=e.getBoundingClientRect();return {y:Math.round(r.y),height:Math.round(r.height)}})()})),titleY:Math.round(document.querySelector('.question-title')?.getBoundingClientRect().top||0)}));
await click('[data-next]');await page.waitForSelector('[name=nome]');await page.type('[name=nome]','Teste Local');await page.type('[name=whatsapp]','11999999999');await click('[data-submit]');const nextstep=await page.evaluate(()=>document.body.innerText.includes('FALTA SÓ UM PASSO:'));if(!nextstep)throw new Error('O envio da captura não abriu T10');report.viewports.push({width:vp.width,titlePositions:ys,result,scrollWidth:await page.evaluate(()=>document.documentElement.scrollWidth)});await page.close()}
await browser.close();server.close();report.payloadKeys=report.payload?Object.keys(report.payload).length:0;report.decimalInPayload=report.payload?Object.values(report.payload).some(v=>v===1.5):false;report.noSituationCounter=!report.viewports.some(x=>x.result.body.includes('Situação '));report.status=report.errors.length===0&&report.external.length===0&&report.payloadKeys===52&&report.noSituationCounter?'PASS':'CHECK';fs.writeFileSync(path.join(out,'gate-v6.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,viewports:report.viewports.map(x=>({width:x.width,titlePositions:x.titlePositions,scrollWidth:x.scrollWidth})),errors:report.errors,external:report.external,payloadKeys:report.payloadKeys,decimalInPayload:report.decimalInPayload,out},null,2));})().catch(e=>{console.error(e);process.exitCode=1;server.close()});


