/* Original WebGL implementation: one quad, colour + authored grayscale depth map. */
(()=>{'use strict';const stage=document.querySelector('.depth-stage');if(!stage)return;const image=stage.querySelector('img'),button=document.querySelector('.depth-button');const reduce=matchMedia('(prefers-reduced-motion: reduce)'),mobile=matchMedia('(max-width:767px)');let gl,canvas,frame=0,program,permission=false,visible=true,ready=false,resizeObserver;const textures=[];let target=[0,0],current=[0,0],offset,buffer;
 function state(s){stage.dataset.state=s}
 function stop(){cancelAnimationFrame(frame);frame=0;state('static')}
 function permitted(){return !reduce.matches&&(!mobile.matches||permission)&&visible&&!document.hidden}
 function draw(){frame=0;if(!ready||!permitted()){stop();return}current=current.map((v,i)=>v+(target[i]-v)*.06);gl.uniform2f(offset,current[0]*.012,current[1]*.012);gl.drawArrays(gl.TRIANGLES,0,6);state('active');frame=requestAnimationFrame(draw)}
 function update(){button.hidden=reduce.matches||!mobile.matches;button.disabled=false;if(permitted()){if(!ready)init();else if(!frame)frame=requestAnimationFrame(draw)}else stop()}
 function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error('shader');return s}
 function texture(img,unit){const t=gl.createTexture();textures.push(t);gl.activeTexture(gl.TEXTURE0+unit);gl.bindTexture(gl.TEXTURE_2D,t);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,img)}
 let initializing=false;async function init(){if(initializing||ready)return;initializing=true;try{await image.decode();const depth=new Image();depth.src='/assets/images/hero/seal-depth.svg';await depth.decode();if(!permitted()){initializing=false;return}canvas=document.createElement('canvas');canvas.setAttribute('aria-hidden','true');gl=canvas.getContext('webgl',{alpha:true,antialias:false,premultipliedAlpha:false,preserveDrawingBuffer:false});if(!gl)throw Error('webgl-unavailable');stage.append(canvas);
 const vs=shader(gl.VERTEX_SHADER,'attribute vec2 p;varying vec2 uv;void main(){uv=p*.5+.5;gl_Position=vec4(p,0.,1.);}');const fs=shader(gl.FRAGMENT_SHADER,'precision mediump float;varying vec2 uv;uniform sampler2D colorMap;uniform sampler2D depthMap;uniform vec2 offset;void main(){float d=texture2D(depthMap,uv).r;vec2 displaced=clamp(uv+offset*(d-.5),vec2(.002),vec2(.998));gl_FragColor=texture2D(colorMap,displaced);}');program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('program');gl.useProgram(program);buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const attr=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(attr);gl.vertexAttribPointer(attr,2,gl.FLOAT,false,0,0);texture(image,0);texture(depth,1);gl.uniform1i(gl.getUniformLocation(program,'colorMap'),0);gl.uniform1i(gl.getUniformLocation(program,'depthMap'),1);offset=gl.getUniformLocation(program,'offset');
 const resize=()=>{const n=Math.min(1400,Math.round(stage.clientWidth*Math.min(devicePixelRatio,2)));canvas.width=n;canvas.height=n;gl.viewport(0,0,n,n)};resizeObserver=new ResizeObserver(resize);resizeObserver.observe(stage);resize();canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();ready=false;stop();button.hidden=true;stage.dataset.fallback='context-lost'});ready=true;update();
 }catch{ready=false;canvas?.remove();state('static');stage.dataset.fallback='unavailable';button.hidden=true;}finally{initializing=false}}
 stage.addEventListener('pointermove',e=>{if(mobile.matches)return;const r=stage.getBoundingClientRect();target=[Math.max(-1,Math.min(1,(e.clientX-r.left)/r.width*2-1)),Math.max(-1,Math.min(1,1-(e.clientY-r.top)/r.height*2))]},{passive:true});stage.addEventListener('pointerleave',()=>target=[0,0]);
 button.addEventListener('click',async()=>{if(permission){permission=false;button.textContent=button.dataset.labelOff||'Ativar profundidade';button.setAttribute('aria-pressed','false');update();return}try{if(typeof DeviceOrientationEvent==='undefined')throw Error('unavailable');if(typeof DeviceOrientationEvent.requestPermission==='function'&&await DeviceOrientationEvent.requestPermission()!=='granted')throw Error('denied');permission=true;button.textContent=button.dataset.labelOn||'Desativar profundidade';button.setAttribute('aria-pressed','true');window.addEventListener('deviceorientation',e=>{if(permission&&e.gamma!==null)target=[Math.max(-1,Math.min(1,e.gamma/30)),Math.max(-1,Math.min(1,(e.beta-45)/30))]},{passive:true});update()}catch{permission=false;button.textContent=button.dataset.labelError||'Profundidade indisponível';button.disabled=true;stop()}});
 new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;update()},{threshold:0}).observe(stage);reduce.addEventListener('change',update);mobile.addEventListener('change',()=>{target=[0,0];update()});document.addEventListener('visibilitychange',update);state('static');update();
})();
