const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const puppeteer=require('C:/Users/zioni/AppData/Local/npm-cache/_npx/0f94ee7615faf582/node_modules/puppeteer-core');
const root=path.resolve(__dirname,'..'),out=path.join(root,'qa','errata');
const config=quiz=>JSON.parse(fs.readFileSync(path.join(root,`public/config/${quiz}.json`),'utf8'));
const state=(step,answers,contact={})=>({step,answers,contact,lead_id:'qa-errata',momento:'A',utm:{},started:true});
async function setPage(browser,quiz,value,width=390){const page=await browser.newPage();await page.setViewport({width,height:width<500?844:1000});await page.evaluateOnNewDocument((key,s)=>sessionStorage.setItem(key,JSON.stringify(s)),`quiz:${quiz}:1.0`,value);await page.goto(`http://127.0.0.1:4173/${quiz}.html`,{waitUntil:'networkidle0'});return page;}
const indexAnswers=(c,point)=>Object.fromEntries(c.steps.filter(s=>s.options).map(s=>[s.key,s.points?s.points.indexOf(point):0]));
(async()=>{const browser=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,userDataDir:path.join(root,'.browser-errata')});const report={flows:[],realFlows:[],copy:[],offers:[],captures:[],errors:[]};fs.mkdirSync(out,{recursive:true});try{
 const p=config('permissao'),s=config('signos');
 for(const [level,point,next] of [['BAIXO',3,'T20'],['MÉDIO',2,'T20'],['ALTO',0,'T23']]){
  const answers=indexAnswers(p,point);answers.p03_formacoes=3;answers.p06_hora_do_preco=level==='ALTO'?2:0;
  const page=await setPage(browser,'permissao',state(18,answers));
  await page.waitForSelector('main[data-step="T19"]');const text=await page.$eval('main',e=>e.innerText);
  assert(text.includes('Você já fez tantas formações que perdeu a conta.'));
  if(level==='ALTO'){assert(text.includes('Aqui a Permissão não aparece como trava.'));assert(text.includes('Vale olhar se isso é trava ou falta de estratégia.'));assert(text.includes('O teste não encontrou uma trava forte de Permissão. Ele não mostra o que mais pode estar segurando o seu resultado.'));}else assert(text.includes('É onde a Permissão aparece primeiro.'));
  if(level==='BAIXO'||level==='ALTO'){await page.screenshot({path:path.join(out,`T19-${level}-390.png`),fullPage:true});report.captures.push(`T19-${level}-390.png`);}
  await page.click('.fixed-action .button');await page.waitForSelector(`main[data-step="${next}"]`);let saved=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('quiz:permissao:1.0')));
  if(level==='ALTO'){assert.equal(saved.answers.p15_disposicao,undefined);assert.equal(saved.answers.p16_acredita,undefined);const rendered=await page.$eval('main',e=>e.innerText);assert(!rendered.includes('Quão disposta você está'));await page.type('#nome','Teste');await page.type('#whatsapp','11999999999');await page.type('#email','teste@example.test');await page.click('button[type=submit]');await page.waitForSelector('main[data-step="T24"]');saved=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('quiz:permissao:1.0')));assert.equal(saved.payload.respostas.p15_disposicao,'');assert.equal(saved.payload.respostas.p16_acredita,'');}
  report.flows.push({level,next,p15:saved.payload?.respostas?.p15_disposicao??saved.answers.p15_disposicao??'',p16:saved.payload?.respostas?.p16_acredita??saved.answers.p16_acredita??''});
  await page.close();
 }
 async function fullFlow(level){const page=await browser.newPage();await page.setViewport({width:390,height:844});await page.goto('http://127.0.0.1:4173/permissao.html?m=B',{waitUntil:'networkidle0'});const seen=[];while(true){const id=await page.$eval('main',e=>e.dataset.step);seen.push(id);if(id==='T24')break;const step=p.steps.find(x=>x.id===id);if(step.options){const point=level==='BAIXO'?3:level==='MÉDIO'?2:0;const choice=step.points?step.points.indexOf(level==='MÉDIO'?(step.points.includes(2)?2:1):point):0;assert.ok(choice>=0,`${id} sem opção para ${level}`);await page.click(`[data-option="${choice}"]`);}else if(step.type==='loading'){await page.waitForFunction(previous=>document.querySelector('main').dataset.step!==previous,{},id);}else if(step.type==='capture'){await page.type('#nome','Teste');await page.type('#whatsapp','11999999999');await page.type('#email','teste@example.test');await page.click('button[type=submit]');}else await page.click('.fixed-action .button');await page.waitForFunction(previous=>document.querySelector('main').dataset.step!==previous,{},id);}
  const saved=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('quiz:permissao:1.0')));assert.equal(saved.payload.resultado,level);assert.equal(await page.$$('.progress').then(x=>x.length),0);assert.equal(await page.$$('.back').then(x=>x.length),0);if(level==='ALTO'){assert.equal(seen.includes('T20'),false);assert.equal(seen.includes('T21'),false);assert.equal(seen.includes('T22'),false);assert.equal(saved.payload.respostas.p15_disposicao,'');assert.equal(saved.payload.respostas.p16_acredita,'');}else{assert.equal(seen.includes('T20'),true);assert.equal(seen.includes('T21'),true);assert.equal(seen.includes('T22'),true);}report.realFlows.push({level,result:saved.payload.resultado,seen,p15:saved.payload.respostas.p15_disposicao,p16:saved.payload.respostas.p16_acredita});await page.close();}
 for(const level of ['BAIXO','MÉDIO','ALTO'])await fullFlow(level);
 for(const width of [360,390,1440]){
  const answers=indexAnswers(p,3);answers.p03_formacoes=3;answers.p06_hora_do_preco=0;let page=await setPage(browser,'permissao',state(18,answers),width);await page.waitForSelector('main[data-step="T19"]');await page.screenshot({path:path.join(root,`qa/screens/permissao/${width}/T19.png`),fullPage:true});await page.close();
  page=await setPage(browser,'permissao',state(23,answers,{nome:'Teste',email:'teste@example.test',whatsapp:'11999999999'}),width);await page.waitForSelector('main[data-step="T24"]');assert.equal(await page.$$('.progress').then(x=>x.length),0);assert.equal(await page.$$('.back').then(x=>x.length),0);await page.screenshot({path:path.join(root,`qa/screens/permissao/${width}/T24.png`),fullPage:true});report.offers.push({quiz:'permissao',width,progress:false,back:false});await page.close();
  const signAnswers=Object.fromEntries(s.steps.filter(x=>x.options).map(x=>[x.key,0]));page=await setPage(browser,'signos',state(12,signAnswers),width);await page.waitForSelector('main[data-step="S13"]');assert((await page.$eval('main',e=>e.innerText)).includes('O conselho te dá uma direção para a semana.'));await page.screenshot({path:path.join(root,`qa/screens/signos/${width}/S13.png`),fullPage:true});await page.close();
  page=await setPage(browser,'signos',state(15,signAnswers,{nome:'Teste',email:'teste@example.test',whatsapp:'11999999999'}),width);await page.waitForSelector('main[data-step="S16"]');assert.equal(await page.$$('.progress').then(x=>x.length),0);assert.equal(await page.$$('.back').then(x=>x.length),0);await page.screenshot({path:path.join(root,`qa/screens/signos/${width}/S16.png`),fullPage:true});report.offers.push({quiz:'signos',width,progress:false,back:false});await page.close();
 }
 report.copy.push('E1','E2','E3','E5');report.complete=true;
}catch(error){report.errors.push(error.stack);console.error(error);process.exitCode=1;}finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report));}})();
