const fs=require('node:fs'),path=require('node:path'),p=require('C:/Users/zioni/AppData/Local/npm-cache/_npx/0f94ee7615faf582/node_modules/puppeteer-core');
const root=path.resolve(__dirname,'..'),qa=path.join(root,'qa'),out=path.join(qa,'pairs');fs.mkdirSync(out,{recursive:true});
const kinds=[['abertura','01','T01','S01'],['pergunta','03','T03','S03'],['insercao','09','T04','S02'],['resultado','32','T19','S13'],['captura','40','T23','S15'],['oferta','41','T24','S16']];
(async()=>{const b=await p.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,userDataDir:path.join(root,'.browser-gallery')});const t=await b.newPage();let links=[];
for(const width of [390,1440])for(const [kind,ref,pstep,sstep]of kinds)for(const [quiz,step]of [['permissao',pstep],['signos',sstep]]){const h=width===390?844:1000;const name=`${width}-${kind}-${quiz}`;const left=`../reference/${ref}-${width===390?'mobile':'desktop'}.png`,right=`../screens/${quiz}/${width}/${step}.png`;
const html=`<!doctype html><meta charset="utf-8"><title>${name}</title><style>body{margin:0;font:14px Arial;background:#eee}header{height:48px;display:flex;align-items:center;padding:0 12px}section{display:flex;gap:16px;padding:0 8px}figure{margin:0;width:${width}px}figcaption{height:28px}img{width:${width}px;display:block}.clip{height:${h}px;overflow:hidden}</style><header>Comparação visual local · ${kind} · ${width}px · ${quiz} · recorte inicial; imagens completas nos links</header><section><figure><figcaption>Referência · tela ${ref}</figcaption><a href="${left}"><div class="clip"><img src="${left}"></div></a></figure><figure><figcaption>Nosso · ${step}</figcaption><a href="${right}"><div class="clip"><img src="${right}"></div></a></figure></section>`;
fs.writeFileSync(path.join(out,name+'.html'),html);await t.setViewport({width:width*2+32,height:h+76});await t.goto('file:///'+path.join(out,name+'.html').replaceAll('\\','/'));await t.screenshot({path:path.join(out,name+'.png'),fullPage:true});links.push(`<li><a href="pairs/${name}.html">${name}</a> · <a href="pairs/${name}.png">PNG</a></li>`);}
let all=[];for(const quiz of ['permissao','signos']){const c=JSON.parse(fs.readFileSync(path.join(root,`public/config/${quiz}.json`)));all.push(`<h2>${quiz} · 390px</h2><div class="grid">${c.steps.map(s=>`<a href="screens/${quiz}/390/${s.id}.png"><strong>${s.id}</strong><img loading="lazy" src="screens/${quiz}/390/${s.id}.png"></a>`).join('')}</div>`);}
fs.writeFileSync(path.join(qa,'index.html'),`<!doctype html><meta charset="utf-8"><title>Evidências dos quizzes</title><style>body{font:16px Arial;margin:24px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.grid img{width:100%;height:420px;object-fit:cover;object-position:top}.grid strong{display:block}</style><h1>Evidências locais</h1><p>Referência arquivada, produção e testes são conjuntos separados. As imagens da referência não fazem parte das páginas dos quizzes.</p><h2>Pares de comparação</h2><ul>${links.join('')}</ul>${all.join('')}`);await b.close();console.log('24 pares PNG/HTML; galeria de 40 telas em qa/index.html');})();
